[set.menuextra.clock]
FlashDateSeparators = false
Show24Hour = false
ShowAMPM = true
ShowDate = 2
ShowDayOfWeek = false
ShowSeconds = false

[set.finder]
AppleShowAllFiles = true
CreateDesktop = false
ShowPathbar = true
ShowExternalHardDrivesOnDesktop = false
FXRemoveOldTrashItems = true
FXEnableExtensionChangeWarning = false
FXDefaultSearchScope = "SCcf"

[set.AppleMultitouchTrackpad]
FirstClickThreshold = 0
TrackpadThreeFingerDrag = true

[set.dock]
tilesize = 50
autohide = true
static-only = true
show-recents = false
magnification = false
orientation = "bottom"
mineffect = "suck"
autohide-delay = 0
autohide-time-modifier = 0
expose-group-apps = false

[set.screencapture]
show-thumbnail = false
target = "clipboard"
type = "png"

[set.NSGlobalDomain]
KeyRepeat = 2
InitialKeyRepeat = 15
NSDocumentSaveNewDocumentsToCloud = false
NSAutomaticInlinePredictionEnabled = false
NSAutomaticSpellingCorrectionEnabled = false
"com.apple.keyboard.fnState" = false

[command.hostname]
run = """
scutil --set ComputerName "Rayâ€™s MacBook Pro"
scutil --set HostName "ray-macbook-pro"
scutil --set LocalHostName "ray-macbook-pro"
"""
ensure_first = true
sudo = true

[brew]
formulae = ["asmvik/formulae/yabai", "oven-sh/bun/bun", "fastfetch", "gnupg", "dmmulroy/tap/jj-starship", "jackielii/tap/skhd-zig", "pinentry-mac", "zoxide", "tree", "machlit/tap/cutler", "fnm", "felixkratz/formulae/borders", "chezmoi", "felixkratz/formulae/sketchybar", "fzf", "helix", "tailscale"]
casks = ["font-sf-pro", "discord@canary", "music-decoy", "superkey", "tailscale-app", "alcove", "raycast", "screen-studio", "little-snitch", "ghostty@tip", "lunar", "slack@beta", "zed@preview", "font-sketchybar-app-font", "orbstack", "thebrowsercompany-dia", "antinote", "spotify"]
taps = ["jackielii/tap", "felixkratz/formulae", "dmmulroy/tap", "oven-sh/bun", "machlit/tap", "mediosz/tap", "nikitabobko/tap", "asmvik/formulae"]
no_deps = true
